### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by NearHuscarl** [dahu/VimCallGraph#1]
Can you put a license to your plugin? I plan to redistribute your plugin but I am not sure if it's permitted

**Comment by dahu** [comment]
This "plugin" was only ever a test-of-concept. It hasn't been polished for release. It hasn't been looked at for 5+ years. I doubt that redistributing this plugin will bring you profit or joy. License added. Good luck.

**Comment by NearHuscarl** [comment]
Thanks. I was searching for something like pycallgraph but in vimscript and your script is the closest I can get so I want to wrap it in a usable plugin for my own use and distribute it for anyone who interest

I will give you full credit of course :smiley_cat:

**Comment by dahu** [comment]
Go for it!
